name: release

on:
  push:
    tags:
      - "v*"

jobs:
  push:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-setup@v2
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push acorn
        run: |
          acorn build --platform linux/amd64 --platform linux/arm64 -t ghcr.io/acorn-io/acorn-dns:$TAG . --tag=$TAG
          acorn push ghcr.io/acorn-io/acorn-dns:$TAG
