name: release

on:
  push:
    tags:
      - "v*"

jobs:
  push:
    runs-on: buildjet-4vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-setup@v1
        with:
          token: ${{ secrets.PULL_TOKEN }}
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: foobar
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push acorn
        run: |
          acorn build -t ghcr.io/acorn-io/acorn-dns:$TAG .
          acorn push ghcr.io/acorn-io/acorn-dns:$TAG
